### ISSUE TITLE
Can't be required directly (coffescript?)

### ISSUE THREAD

**Issue by jfirebaugh** [claydotio/zock#4]
I did `npm install --save-dev zock`, then added `var zock = require('zock')` to a test file. When running tests, I get the following error:

```
/Users/john/Development/api-gl/node_modules/zock/src/index.coffee:1
ction (exports, require, module, __filename, __dirname) { _ = require 'lodash'
                                                                      ^^^^^^^^
SyntaxError: Unexpected string
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/john/Development/api-gl/test/embed.test.js:6:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

How can I avoid this error? Would you consider changing the package on npm to have a compiled JS file rather than coffescript, so a coffescript dependency could be avoided for zock's dependents?

**Comment by Zolmeister** [comment]
To your error:
You're missing coffeescript
`require('coffee-script/register')` before requiring zock (for node) or run using the coffeescript binary

As for compiling zock to js, I could be open to it. I'd have to look into node source-mapping and how it might affect client-side compilation source-maps. Open to PR which accounts for these problems

**Comment by jfirebaugh** [comment]
> `require('coffee-script/register')`

Could this be documented in the README?

**Comment by Zolmeister** [comment]
Added

**Comment by jfirebaugh** [comment]
Thank you!

**Comment by justrhysism** [comment]
It should be possible to use this module without having to add dependencies to our projects.

The fact that you develop it in coffeescript should be irrelevant and have no bearing on projects wanting to consume this module.

There’s plenty of examples about publishing AMD and CJS (among others) into a `/dist` directory.
